### ISSUE TITLE
请教一个wp-xhprof的问题

### ISSUE THREAD

**Issue by gaoyong06** [0xJacky/wp-xhprof#1]
从下面这篇文章
https://jackyu.cn/tech/xhprof/

看到 https://github.com/0xJacky/wp-xhprof 这个项目, 但是因为这个仓库没有开issues，没法提问，所以在这里问下

按照 https://github.com/0xJacky/wp-xhprof 的说明，已经启用了wp-xhprof

问题是：你上面博客中的“于是 xhprof 及 wp-xhprof 插件就部署上了，打开插件后，在页面的底部会生成指向分析报告的 Profiler output”

在哪里打开插件？入口是哪里？找了半天没找到哈

![20231206115930](https://github.com/0xJacky/nginx-ui/assets/1861256/a88d068c-5f75-43ff-9cae-6ea958997d97)

**Comment by 0xJacky** [comment]
WordPress 改 API 了吧，这个项目已经两年没有维护了，上次修订还是 21 年 8 月，我过阵子有空看看，有能力的话也可以直接改代码

**Comment by 0xJacky** [comment]
原作者用了这个 hook：https://github.com/0xJacky/wp-xhprof/blob/156c24384ae47a6e85eeb0d3afb836decc357638/wp-xhprof.php#L23

现在被 marked as private 了：https://developer.wordpress.org/reference/functions/shutdown_action_hook/

换个 hook 应该就可以

**Comment by 0xJacky** [comment]
参考 readme.md，把这个代码添加到 wp-config.php 中

require_once(ABSPATH . 'wp-content/plugins/wp-xhprof/xhprof-loader.php');
